language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 2.7
    - os: osx
      language: generic

install:
  - ./.travis-install.sh
script: make tests
after_success:
  - coveralls
services:
  - memcached
  - redis-server