language: python

matrix:
  include:
    - os: linux
      python: 2.7
    - os: osx
      language: generic
      env: TOXENV=py27

install:
  - ./travis-install.sh
script: make tests
after_success:
  - coveralls
services:
  - memcached
  - redis-server