language: python
python:
  - "2.7"
  - "pypy"
install:
  - pip install -U coveralls
script:
  - coverage run --source=vishnu setup.py test
after_success:
  - coveralls
notifications:
  email: false

services:
  - memcached
  - redis-server